"""Add timestamps to comms tables

Revision ID: 1b2123b33776
Revises: 2545c1792d7c
Create Date: 2026-04-09 17:52:33.834361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b2123b33776'
down_revision: Union[str, Sequence[str], None] = '2545c1792d7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails_v2', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('emails_v2', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('reunions_v2', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('reunions_v2', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('trucades_v2', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('trucades_v2', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trucades_v2', 'updated_at')
    op.drop_column('trucades_v2', 'created_at')
    op.drop_column('reunions_v2', 'updated_at')
    op.drop_column('reunions_v2', 'created_at')
    op.drop_column('emails_v2', 'updated_at')
    op.drop_column('emails_v2', 'created_at')
    # ### end Alembic commands ###
