"""Add tracking_token to emails_v2

Revision ID: 2545c1792d7c
Revises: 6edbb11833e0
Create Date: 2026-04-09 17:51:30.025224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2545c1792d7c'
down_revision: Union[str, Sequence[str], None] = '6edbb11833e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails_v2', sa.Column('tracking_token', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'emails_v2', ['tracking_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'emails_v2', type_='unique')
    op.drop_column('emails_v2', 'tracking_token')
    # ### end Alembic commands ###
