"""Add tracking fields to emails for Phase 3

Revision ID: 4207161759da
Revises: 9714405b673c
Create Date: 2026-03-10 21:23:34.798783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4207161759da'
down_revision: Union[str, Sequence[str], None] = '9714405b673c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('tracking_token', sa.String(length=100), nullable=True))
    op.add_column('emails', sa.Column('obert', sa.Boolean(), nullable=True))
    op.add_column('emails', sa.Column('data_obertura', sa.DateTime(timezone=True), nullable=True))
    op.add_column('emails', sa.Column('nombre_obertures', sa.Integer(), nullable=True))
    op.add_column('emails', sa.Column('ip_obertura', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'emails', ['tracking_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'emails', type_='unique')
    op.drop_column('emails', 'ip_obertura')
    op.drop_column('emails', 'nombre_obertures')
    op.drop_column('emails', 'data_obertura')
    op.drop_column('emails', 'obert')
    op.drop_column('emails', 'tracking_token')
    # ### end Alembic commands ###
