"""Add contacte_id and direccio columns to comms tables

Revision ID: 6edbb11833e0
Revises: d2e76c3d5531
Create Date: 2026-04-09 17:50:56.255283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6edbb11833e0'
down_revision: Union[str, Sequence[str], None] = 'd2e76c3d5531'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails_v2', sa.Column('contacte_id', sa.UUID(), nullable=True))
    op.add_column('emails_v2', sa.Column('direccio', sa.String(length=10), nullable=True))
    op.create_foreign_key(None, 'emails_v2', 'contactes_v2', ['contacte_id'], ['id'])
    op.add_column('reunions_v2', sa.Column('contacte_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'reunions_v2', 'contactes_v2', ['contacte_id'], ['id'])
    op.add_column('trucades_v2', sa.Column('contacte_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'trucades_v2', 'contactes_v2', ['contacte_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trucades_v2', type_='foreignkey')
    op.drop_column('trucades_v2', 'contacte_id')
    op.drop_constraint(None, 'reunions_v2', type_='foreignkey')
    op.drop_column('reunions_v2', 'contacte_id')
    op.drop_constraint(None, 'emails_v2', type_='foreignkey')
    op.drop_column('emails_v2', 'direccio')
    op.drop_column('emails_v2', 'contacte_id')
    # ### end Alembic commands ###
