"""Afegir taula tasques

Revision ID: 8ea70128ae08
Revises: 9949dda77011
Create Date: 2026-03-11 21:48:14.503819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ea70128ae08'
down_revision: Union[str, Sequence[str], None] = '9949dda77011'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasques',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deal_id', sa.UUID(), nullable=True),
    sa.Column('contacte_id', sa.UUID(), nullable=True),
    sa.Column('municipi_id', sa.UUID(), nullable=True),
    sa.Column('usuari_id', sa.UUID(), nullable=True),
    sa.Column('titol', sa.String(length=300), nullable=False),
    sa.Column('descripcio', sa.Text(), nullable=True),
    sa.Column('data_venciment', sa.Date(), nullable=False),
    sa.Column('tipus', sa.String(length=50), nullable=True),
    sa.Column('prioritat', sa.String(length=20), nullable=True),
    sa.Column('estat', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['contacte_id'], ['contactes.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.ForeignKeyConstraint(['municipi_id'], ['municipis.id'], ),
    sa.ForeignKeyConstraint(['usuari_id'], ['usuaris.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasques')
    # ### end Alembic commands ###
