"""Add hierarchical memory tables and fields

Revision ID: 96cbc1328ae4
Revises: 36c92d68a081
Create Date: 2026-04-09 18:13:34.346954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '96cbc1328ae4'
down_revision: Union[str, Sequence[str], None] = '36c92d68a081'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memoria_global',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('llico', sa.Text(), nullable=False),
    sa.Column('evidencia', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confianca', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('agent_memories_v2', sa.Column('usuari_id', sa.UUID(), nullable=True))
    op.add_column('agent_memories_v2', sa.Column('session_id', sa.UUID(), nullable=True))
    op.add_column('agent_memories_v2', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('agent_memories_v2', sa.Column('history', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('agent_memories_v2', sa.Column('summary', sa.Text(), nullable=True))
    op.create_index(op.f('ix_agent_memories_v2_session_id'), 'agent_memories_v2', ['session_id'], unique=False)
    op.create_foreign_key(None, 'agent_memories_v2', 'usuaris', ['usuari_id'], ['id'])
    op.add_column('memoria_municipis', sa.Column('resum_setmanal', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memoria_municipis', 'resum_setmanal')
    op.drop_constraint(None, 'agent_memories_v2', type_='foreignkey')
    op.drop_index(op.f('ix_agent_memories_v2_session_id'), table_name='agent_memories_v2')
    op.drop_column('agent_memories_v2', 'summary')
    op.drop_column('agent_memories_v2', 'history')
    op.drop_column('agent_memories_v2', 'expires_at')
    op.drop_column('agent_memories_v2', 'session_id')
    op.drop_column('agent_memories_v2', 'usuari_id')
    op.drop_table('memoria_global')
    # ### end Alembic commands ###
