"""Initial schema and Phase 2

Revision ID: 9714405b673c
Revises: 
Create Date: 2026-03-10 17:47:51.959199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9714405b673c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('municipis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('tipus', sa.String(length=50), nullable=False),
    sa.Column('provincia', sa.String(length=100), nullable=True),
    sa.Column('poblacio', sa.Integer(), nullable=True),
    sa.Column('web', sa.String(length=255), nullable=True),
    sa.Column('telefon', sa.String(length=50), nullable=True),
    sa.Column('adreca', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuaris',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=True),
    sa.Column('actiu', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('contactes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('municipi_id', sa.UUID(), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('carrec', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telefon', sa.String(length=50), nullable=True),
    sa.Column('linkedin', sa.String(length=255), nullable=True),
    sa.Column('notes_humanes', sa.Text(), nullable=True),
    sa.Column('actiu', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['municipi_id'], ['municipis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('municipi_id', sa.UUID(), nullable=False),
    sa.Column('contacte_id', sa.UUID(), nullable=True),
    sa.Column('titol', sa.String(length=300), nullable=False),
    sa.Column('etapa', sa.String(length=50), nullable=False),
    sa.Column('valor_setup', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('valor_llicencia', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('prioritat', sa.String(length=20), nullable=True),
    sa.Column('notes_humanes', sa.Text(), nullable=True),
    sa.Column('proper_pas', sa.Text(), nullable=True),
    sa.Column('data_seguiment', sa.Date(), nullable=True),
    sa.Column('data_tancament_prev', sa.Date(), nullable=True),
    sa.Column('data_tancament_real', sa.Date(), nullable=True),
    sa.Column('motiu_perdua', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['contacte_id'], ['contactes.id'], ),
    sa.ForeignKeyConstraint(['municipi_id'], ['municipis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emails',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deal_id', sa.UUID(), nullable=True),
    sa.Column('contacte_id', sa.UUID(), nullable=True),
    sa.Column('campanya_id', sa.UUID(), nullable=True),
    sa.Column('from_address', sa.String(length=255), nullable=False),
    sa.Column('to_address', sa.String(length=255), nullable=False),
    sa.Column('assumpte', sa.String(length=500), nullable=False),
    sa.Column('cos', sa.Text(), nullable=True),
    sa.Column('direccio', sa.String(length=3), nullable=False),
    sa.Column('llegit', sa.Boolean(), nullable=True),
    sa.Column('sincronitzat', sa.Boolean(), nullable=True),
    sa.Column('message_id_extern', sa.String(length=500), nullable=True),
    sa.Column('data_email', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['contacte_id'], ['contactes.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id_extern')
    )
    op.create_table('llicencies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('data_inici', sa.Date(), nullable=False),
    sa.Column('data_renovacio', sa.Date(), nullable=False),
    sa.Column('estat', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deal_id')
    )
    op.create_table('pagaments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('llicencia_id', sa.UUID(), nullable=False),
    sa.Column('import', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tipus', sa.String(length=50), nullable=False),
    sa.Column('estat', sa.String(length=50), nullable=True),
    sa.Column('data_emisio', sa.Date(), nullable=False),
    sa.Column('data_limit', sa.Date(), nullable=True),
    sa.Column('data_confirmacio', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['llicencia_id'], ['llicencies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pagaments')
    op.drop_table('llicencies')
    op.drop_table('emails')
    op.drop_table('deals')
    op.drop_table('contactes')
    op.drop_table('usuaris')
    op.drop_table('municipis')
    # ### end Alembic commands ###
