"""Add deal_activitats table for Phase 3 context

Revision ID: 9949dda77011
Revises: 4207161759da
Create Date: 2026-03-10 21:25:11.097917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9949dda77011'
down_revision: Union[str, Sequence[str], None] = '4207161759da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deal_activitats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('tipus', sa.String(length=50), nullable=False),
    sa.Column('descripcio', sa.Text(), nullable=False),
    sa.Column('valor_anterior', sa.String(length=255), nullable=True),
    sa.Column('valor_nou', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deal_activitats')
    # ### end Alembic commands ###
