"""codi postal

Revision ID: a3f5e76d049d
Revises: e40234ee066b
Create Date: 2026-03-24 09:54:38.514525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3f5e76d049d'
down_revision: Union[str, Sequence[str], None] = 'e40234ee066b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('municipis', sa.Column('codi_postal', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('municipis', 'codi_postal')
    # ### end Alembic commands ###
