"""Remove AI tables and columns

Revision ID: ad9ce4b0fbaf
Revises: 737f14652d0c
Create Date: 2026-04-22 12:12:56.678947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ad9ce4b0fbaf'
down_revision: Union[str, Sequence[str], None] = '737f14652d0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_memories_v2_clau'), table_name='agent_memories')
    op.drop_index(op.f('ix_agent_memories_v2_session_id'), table_name='agent_memories')
    op.drop_index(op.f('ix_agent_memories_v2_usuari_id'), table_name='agent_memories')
    op.drop_constraint(op.f('activitats_municipi_deal_id_fkey'), 'activitats', type_='foreignkey')
    op.drop_constraint(op.f('llicencies_deal_id_fkey'), 'llicencies', type_='foreignkey')
    op.drop_table('agent_memories')
    op.drop_table('memoria_municipis')
    op.drop_table('email_sequencies')
    op.drop_table('email_drafts')
    op.drop_table('agent_memories_v1_backup')
    op.drop_table('tasques_v1_backup')
    op.drop_table('emails_v1_backup')
    op.drop_table('deal_activitats')
    op.drop_table('deals_v1_backup')
    op.drop_table('contactes_v1_backup')
    op.drop_table('municipis_v1_backup')
    op.drop_table('patrons_municipis')
    op.drop_table('memoria_global')
    op.alter_column('activitats', 'tipus_activitat',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.Enum('nota_manual', 'email_enviat', 'email_rebut', 'trucada', 'reunio', 'demo', 'pagament', 'canvi_etapa', 'sistema', name='tipus_activitat'),
               existing_nullable=False,
               postgresql_using='tipus_activitat::tipus_activitat')
    op.drop_index(op.f('ix_activitats_contingut_gin'), table_name='activitats', postgresql_using='gin')
    op.drop_index(op.f('ix_activitats_municipi_data'), table_name='activitats')
    op.drop_index(op.f('ix_activitats_municipi_data_activitat'), table_name='activitats')
    op.drop_index(op.f('ix_activitats_municipi_municipi_id'), table_name='activitats')
    op.drop_index(op.f('ix_activitats_municipi_tipus'), table_name='activitats')
    op.drop_index(op.f('ix_activitats_municipi_tipus_activitat'), table_name='activitats')
    op.create_index(op.f('ix_activitats_data_activitat'), 'activitats', ['data_activitat'], unique=False)
    op.create_index(op.f('ix_activitats_municipi_id'), 'activitats', ['municipi_id'], unique=False)
    op.create_index(op.f('ix_activitats_tipus_activitat'), 'activitats', ['tipus_activitat'], unique=False)
    op.drop_column('activitats', 'deal_id')
    op.drop_column('activitats', 'generat_per_ia')
    op.alter_column('contactes', 'carrec',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=100),
               nullable=True)
    op.alter_column('contactes', 'to_preferit',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('emails', 'municipi_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('emails', 'sentiment_resposta',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('emails', 'actor_probable',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.create_unique_constraint(None, 'emails', ['message_id_extern'])
    op.add_column('llicencies', sa.Column('import', sa.Numeric(precision=10, scale=2), nullable=True))
    op.alter_column('llicencies', 'data_renovacio',
               existing_type=sa.DATE(),
               nullable=True)
    op.create_foreign_key(None, 'llicencies', 'municipis', ['deal_id'], ['id'])
    op.drop_column('llicencies', 'updated_at')
    op.drop_column('llicencies', 'notes')
    op.alter_column('municipis', 'blocker_actual',
               existing_type=sa.VARCHAR(length=13),
               type_=sa.Enum('alcalde', 'tecnic', 'cfo', 'temporitzacio', 'cap', name='blocker'),
               existing_nullable=True,
               existing_server_default=sa.text("'cap'::blocker"),
               postgresql_using='blocker_actual::blocker')
    op.alter_column('municipis', 'temperatura',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('fred', 'templat', 'calent', 'bullent', name='temperatura'),
               existing_nullable=True,
               existing_server_default=sa.text("'fred'::temperatura"),
               postgresql_using='temperatura::temperatura')
    op.alter_column('municipis', 'pla_contractat',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('Roure', 'Mirador', 'Territori', name='pla'),
               existing_nullable=True,
               postgresql_using='pla_contractat::pla')
    op.alter_column('municipis', 'estat_final',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.Enum('client', 'perdut', 'pausa', name='estat_final'),
               existing_nullable=True,
               postgresql_using='estat_final::estat_final')
    op.drop_index(op.f('ix_municipis_lifecycle_etapa_actual'), table_name='municipis')
    op.drop_index(op.f('ix_municipis_lifecycle_nom'), table_name='municipis')
    op.create_index(op.f('ix_municipis_etapa_actual'), 'municipis', ['etapa_actual'], unique=False)
    op.create_index(op.f('ix_municipis_nom'), 'municipis', ['nom'], unique=False)
    op.alter_column('pagaments', 'tipus',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('pagaments', 'updated_at')
    op.drop_column('pagaments', 'notes')
    op.alter_column('reunions', 'temperatura_post',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('fred', 'templat', 'calent', 'bullent', name='temperatura_post'),
               existing_nullable=True,
               postgresql_using='temperatura_post::temperatura_post')
    op.alter_column('tasques', 'municipi_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('tasques', 'titol',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('tasques', 'data_venciment',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('tasques', 'estat',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'pendent'::character varying"))
    op.drop_column('tasques', 'usuari_id')
    op.drop_column('tasques', 'tipus')
    op.drop_column('tasques', 'metadata')
    op.alter_column('trucades', 'qui_va_contestar',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('alcalde', 'tecnic', 'cfo', name='actor_respuesta'),
               existing_nullable=True,
               postgresql_using='qui_va_contestar::actor_respuesta')
    op.drop_column('trucades', 'resum_ia')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trucades', sa.Column('resum_ia', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('trucades', 'qui_va_contestar',
               existing_type=sa.Enum('alcalde', 'tecnic', 'cfo', name='actor_respuesta'),
               type_=sa.VARCHAR(length=7),
               existing_nullable=True)
    op.add_column('tasques', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True))
    op.add_column('tasques', sa.Column('tipus', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('tasques', sa.Column('usuari_id', sa.UUID(), autoincrement=False, nullable=True))
    op.alter_column('tasques', 'estat',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'pendent'::character varying"))
    op.alter_column('tasques', 'data_venciment',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('tasques', 'titol',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('tasques', 'municipi_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('reunions', 'temperatura_post',
               existing_type=sa.Enum('fred', 'templat', 'calent', 'bullent', name='temperatura_post'),
               type_=sa.VARCHAR(length=7),
               existing_nullable=True)
    op.add_column('pagaments', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('pagaments', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.alter_column('pagaments', 'tipus',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_municipis_nom'), table_name='municipis')
    op.drop_index(op.f('ix_municipis_etapa_actual'), table_name='municipis')
    op.create_index(op.f('ix_municipis_lifecycle_nom'), 'municipis', ['nom'], unique=False)
    op.create_index(op.f('ix_municipis_lifecycle_etapa_actual'), 'municipis', ['etapa_actual'], unique=False)
    op.alter_column('municipis', 'estat_final',
               existing_type=sa.Enum('client', 'perdut', 'pausa', name='estat_final'),
               type_=sa.VARCHAR(length=6),
               existing_nullable=True)
    op.alter_column('municipis', 'pla_contractat',
               existing_type=sa.Enum('Roure', 'Mirador', 'Territori', name='pla'),
               type_=sa.VARCHAR(length=9),
               existing_nullable=True)
    op.alter_column('municipis', 'temperatura',
               existing_type=sa.Enum('fred', 'templat', 'calent', 'bullent', name='temperatura'),
               type_=sa.VARCHAR(length=7),
               existing_nullable=True,
               existing_server_default=sa.text("'fred'::temperatura"))
    op.alter_column('municipis', 'blocker_actual',
               existing_type=sa.Enum('alcalde', 'tecnic', 'cfo', 'temporitzacio', 'cap', name='blocker'),
               type_=sa.VARCHAR(length=13),
               existing_nullable=True,
               existing_server_default=sa.text("'cap'::blocker"))
    op.add_column('llicencies', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('llicencies', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'llicencies', type_='foreignkey')
    op.create_foreign_key(op.f('llicencies_deal_id_fkey'), 'llicencies', 'deals_v1_backup', ['deal_id'], ['id'])
    op.alter_column('llicencies', 'data_renovacio',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('llicencies', 'import')
    op.drop_constraint(None, 'emails', type_='unique')
    op.alter_column('emails', 'actor_probable',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=7),
               existing_nullable=True)
    op.alter_column('emails', 'sentiment_resposta',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=7),
               existing_nullable=True)
    op.alter_column('emails', 'municipi_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('contactes', 'to_preferit',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=6),
               existing_nullable=True)
    op.alter_column('contactes', 'carrec',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=15),
               nullable=False)
    op.add_column('activitats', sa.Column('generat_per_ia', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('activitats', sa.Column('deal_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('activitats_municipi_deal_id_fkey'), 'activitats', 'deals_v1_backup', ['deal_id'], ['id'])
    op.drop_index(op.f('ix_activitats_tipus_activitat'), table_name='activitats')
    op.drop_index(op.f('ix_activitats_municipi_id'), table_name='activitats')
    op.drop_index(op.f('ix_activitats_data_activitat'), table_name='activitats')
    op.create_index(op.f('ix_activitats_municipi_tipus_activitat'), 'activitats', ['tipus_activitat'], unique=False)
    op.create_index(op.f('ix_activitats_municipi_tipus'), 'activitats', ['tipus_activitat'], unique=False)
    op.create_index(op.f('ix_activitats_municipi_municipi_id'), 'activitats', ['municipi_id'], unique=False)
    op.create_index(op.f('ix_activitats_municipi_data_activitat'), 'activitats', ['data_activitat'], unique=False)
    op.create_index(op.f('ix_activitats_municipi_data'), 'activitats', ['data_activitat'], unique=False)
    op.create_index(op.f('ix_activitats_contingut_gin'), 'activitats', ['contingut'], unique=False, postgresql_using='gin')
    op.alter_column('activitats', 'tipus_activitat',
               existing_type=sa.Enum('nota_manual', 'email_enviat', 'email_rebut', 'trucada', 'reunio', 'demo', 'pagament', 'canvi_etapa', 'sistema', name='tipus_activitat'),
               type_=sa.VARCHAR(length=12),
               existing_nullable=False)
    op.create_table('memoria_global',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('categoria', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('llico', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('evidencia', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('confianca', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('memoria_global_pkey'))
    )
    op.create_table('deals_v1_backup',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('municipi_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('contacte_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('titol', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('etapa', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('valor_setup', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('valor_llicencia', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('prioritat', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('notes_humanes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('proper_pas', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('data_seguiment', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('data_tancament_prev', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('data_tancament_real', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('motiu_perdua', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['contacte_id'], ['contactes_v1_backup.id'], name=op.f('deals_contacte_id_fkey')),
    sa.ForeignKeyConstraint(['municipi_id'], ['municipis_v1_backup.id'], name=op.f('deals_municipi_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('deals_pkey'))
    )
    op.create_table('patrons_municipis',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('rang_poblacio', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('tipus_geografia', sa.VARCHAR(length=8), autoincrement=False, nullable=True),
    sa.Column('context_politic', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('probabilitat_conversio', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=True),
    sa.Column('temps_mitja_cicle_dies', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('etapa_bloqueig_frequent', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('estrategia_recomanada', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('objeccions_frequents', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('casos_exit_referencia', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('cops_aplicat', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('exitosos', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('patrons_municipis_pkey'))
    )
    op.create_table('email_sequencies',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('municipi_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('numero_email', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tipus_sequencia', sa.VARCHAR(length=11), autoincrement=False, nullable=False),
    sa.Column('estat', sa.VARCHAR(length=9), server_default=sa.text("'pendent'::estat_sequencia"), autoincrement=False, nullable=True),
    sa.Column('data_programada', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('data_enviada', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('draft_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('obert', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('data_obertura', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('respost', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('seguent_accio', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['draft_id'], ['email_drafts.id'], name=op.f('email_sequencies_v2_draft_id_fkey')),
    sa.ForeignKeyConstraint(['municipi_id'], ['municipis.id'], name=op.f('email_sequencies_v2_municipi_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('email_sequencies_v2_pkey'))
    )
    op.create_table('agent_memories_v1_backup',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('usuari_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('deal_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('municipi_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('history', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals_v1_backup.id'], name=op.f('agent_memories_deal_id_fkey')),
    sa.ForeignKeyConstraint(['municipi_id'], ['municipis_v1_backup.id'], name=op.f('agent_memories_municipi_id_fkey')),
    sa.ForeignKeyConstraint(['usuari_id'], ['usuaris.id'], name=op.f('agent_memories_usuari_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('agent_memories_pkey'))
    )
    op.create_table('tasques_v1_backup',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('deal_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('contacte_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('municipi_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('usuari_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('titol', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('descripcio', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('data_venciment', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('tipus', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('prioritat', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('estat', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['contacte_id'], ['contactes_v1_backup.id'], name=op.f('tasques_contacte_id_fkey')),
    sa.ForeignKeyConstraint(['deal_id'], ['deals_v1_backup.id'], name=op.f('tasques_deal_id_fkey')),
    sa.ForeignKeyConstraint(['municipi_id'], ['municipis_v1_backup.id'], name=op.f('tasques_municipi_id_fkey')),
    sa.ForeignKeyConstraint(['usuari_id'], ['usuaris.id'], name=op.f('tasques_usuari_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('tasques_pkey'))
    )
    op.create_table('deal_activitats',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('deal_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tipus', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('descripcio', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('valor_anterior', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('valor_nou', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals_v1_backup.id'], name=op.f('deal_activitats_deal_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('deal_activitats_pkey'))
    )
    op.create_table('municipis_v1_backup',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('nom', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tipus', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('provincia', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('poblacio', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('web', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('telefon', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('adreca', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('codi_postal', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('municipis_pkey'))
    )
    op.create_table('contactes_v1_backup',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('municipi_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('nom', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('carrec', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('telefon', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('linkedin', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('notes_humanes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('actiu', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['municipi_id'], ['municipis_v1_backup.id'], name=op.f('contactes_municipi_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('contactes_pkey'))
    )
    op.create_table('emails_v1_backup',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('deal_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('contacte_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('campanya_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('from_address', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('to_address', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('assumpte', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cos', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('direccio', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('llegit', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('sincronitzat', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('message_id_extern', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('data_email', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('tracking_token', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('obert', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('data_obertura', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('nombre_obertures', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ip_obertura', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['contacte_id'], ['contactes_v1_backup.id'], name=op.f('emails_contacte_id_fkey')),
    sa.ForeignKeyConstraint(['deal_id'], ['deals_v1_backup.id'], name=op.f('emails_deal_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('emails_pkey')),
    sa.UniqueConstraint('message_id_extern', name=op.f('emails_message_id_extern_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('tracking_token', name=op.f('emails_tracking_token_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('email_drafts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('municipi_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('contacte_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('estat', sa.VARCHAR(length=9), server_default=sa.text("'esborrany'::estat_draft"), autoincrement=False, nullable=True),
    sa.Column('subject', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('cos', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('generat_per_ia', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('prompt_utilitzat', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('variants_generades', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('variant_seleccionada', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('editat_per_usuari', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('canvis_respecte_ia', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('data_enviament', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('enviat_des_de', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('email_enviat_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['contacte_id'], ['contactes.id'], name=op.f('email_drafts_v2_contacte_id_fkey')),
    sa.ForeignKeyConstraint(['email_enviat_id'], ['emails.id'], name=op.f('email_drafts_v2_email_enviat_id_fkey')),
    sa.ForeignKeyConstraint(['municipi_id'], ['municipis.id'], name=op.f('email_drafts_v2_municipi_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('email_drafts_v2_pkey'))
    )
    op.create_table('memoria_municipis',
    sa.Column('municipi_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('ganxos_exitosos', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('angles_fallits', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('moment_optimal', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('llenguatge_preferit', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('blockers_resolts', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('data_actualitzacio', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('resum_tactic', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('data_resum', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('resum_setmanal', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['municipi_id'], ['municipis.id'], name=op.f('memoria_municipis_municipi_id_fkey')),
    sa.PrimaryKeyConstraint('municipi_id', name=op.f('memoria_municipis_pkey'))
    )
    op.create_table('agent_memories',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('municipi_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('usuari_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('deal_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('history', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('clau', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('valor', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('confianca', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['municipi_id'], ['municipis.id'], name=op.f('agent_memories_v2_municipi_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('agent_memories_v2_pkey'))
    )
    op.create_index(op.f('ix_agent_memories_v2_usuari_id'), 'agent_memories', ['usuari_id'], unique=False)
    op.create_index(op.f('ix_agent_memories_v2_session_id'), 'agent_memories', ['session_id'], unique=False)
    op.create_index(op.f('ix_agent_memories_v2_clau'), 'agent_memories', ['clau'], unique=False)
    # ### end Alembic commands ###
