"""create_v2

Revision ID: cbd00bad276d
Revises: 8ea70128ae08
Create Date: 2026-03-17 21:01:27.385033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cbd00bad276d'
down_revision: Union[str, Sequence[str], None] = '8ea70128ae08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Create municipis_lifecycle FIRST (without circular FK to contactes_v2)
    op.create_table('municipis_lifecycle',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('comarca', sa.String(length=50), nullable=True),
    sa.Column('poblacio', sa.Integer(), nullable=True),
    sa.Column('geografia', sa.Enum('muntanya', 'mar', 'interior', 'city', name='geografia'), nullable=True),
    sa.Column('diagnostic_digital', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('angle_personalitzacio', sa.Text(), nullable=True),
    sa.Column('etapa_actual', sa.Enum('research', 'contacte', 'demo_pendent', 'demo_ok', 'oferta', 'documentacio', 'aprovacio', 'contracte', 'client', 'pausa', 'perdut', name='etapa_funnel'), nullable=True),
    sa.Column('historial_etapes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('blocker_actual', sa.Enum('alcalde', 'tecnic', 'cfo', 'temporitzacio', 'cap', name='blocker'), nullable=True),
    sa.Column('temperatura', sa.Enum('fred', 'templat', 'calent', 'bullent', name='temperatura'), nullable=True),
    sa.Column('dies_etapa_actual', sa.Integer(), nullable=True),
    sa.Column('data_conversio', sa.DateTime(), nullable=True),
    sa.Column('pla_contractat', sa.Enum('Roure', 'Mirador', 'Territori', name='pla'), nullable=True),
    sa.Column('estat_final', sa.Enum('client', 'perdut', 'pausa', name='estat_final'), nullable=True),
    sa.Column('actor_principal_id', sa.UUID(), nullable=True),
    sa.Column('data_creacio', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('data_ultima_accio', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('usuari_asignat', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_municipis_lifecycle_etapa_actual'), 'municipis_lifecycle', ['etapa_actual'], unique=False)
    op.create_index(op.f('ix_municipis_lifecycle_nom'), 'municipis_lifecycle', ['nom'], unique=False)

    # 2. Create contactes_v2 (with FK to municipis_lifecycle)
    op.create_table('contactes_v2',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('municipi_id', sa.UUID(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('carrec', sa.Enum('alcalde', 'regidor_turisme', 'tecnic', 'cfo', 'regidor_cultura', 'altre', name='carrec'), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('telefon', sa.String(length=20), nullable=True),
    sa.Column('actiu', sa.Boolean(), nullable=True),
    sa.Column('principal', sa.Boolean(), nullable=True),
    sa.Column('angles_exitosos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('angles_fallits', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('moment_optimal', sa.String(length=10), nullable=True),
    sa.Column('to_preferit', sa.Enum('formal', 'proxim', 'tecnic', name='to_comunicacio'), nullable=True),
    sa.Column('data_creacio', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['municipi_id'], ['municipis_lifecycle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # 3. Add the circular FK explicitly
    op.create_foreign_key('fk_municipi_actor_principal', 'municipis_lifecycle', 'contactes_v2', ['actor_principal_id'], ['id'])

    # 4. Create remaining tables
    op.create_table('patrons_municipis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rang_poblacio', sa.String(length=20), nullable=True),
    sa.Column('tipus_geografia', sa.Enum('muntanya', 'mar', 'interior', 'city', name='geografia_patro'), nullable=True),
    sa.Column('context_politic', sa.String(length=20), nullable=True),
    sa.Column('probabilitat_conversio', sa.Float(), nullable=True),
    sa.Column('temps_mitja_cicle_dies', sa.Integer(), nullable=True),
    sa.Column('etapa_bloqueig_frequent', sa.String(length=50), nullable=True),
    sa.Column('estrategia_recomanada', sa.Text(), nullable=True),
    sa.Column('objeccions_frequents', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('casos_exit_referencia', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cops_aplicat', sa.Integer(), nullable=True),
    sa.Column('exitosos', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emails_v2',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('municipi_id', sa.UUID(), nullable=False),
    sa.Column('data_enviament', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('assumpte', sa.String(length=200), nullable=True),
    sa.Column('cos', sa.Text(), nullable=True),
    sa.Column('obert', sa.Boolean(), nullable=True),
    sa.Column('data_obertura', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cops_obert', sa.Integer(), nullable=True),
    sa.Column('respost', sa.Boolean(), nullable=True),
    sa.Column('data_resposta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sentiment_resposta', sa.Enum('positiu', 'neutre', 'negatiu', 'confus', name='sentiment'), nullable=True),
    sa.Column('intents_detectats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('actor_probable', sa.Enum('alcalde', 'tecnic', 'cfo', name='actor'), nullable=True),
    sa.ForeignKeyConstraint(['municipi_id'], ['municipis_lifecycle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memoria_municipis',
    sa.Column('municipi_id', sa.UUID(), nullable=False),
    sa.Column('ganxos_exitosos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('angles_fallits', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('moment_optimal', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('llenguatge_preferit', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('blockers_resolts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('data_actualitzacio', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['municipi_id'], ['municipis_lifecycle.id'], ),
    sa.PrimaryKeyConstraint('municipi_id')
    )
    op.create_table('reunions_v2',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('municipi_id', sa.UUID(), nullable=False),
    sa.Column('data', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tipus', sa.String(length=20), nullable=True),
    sa.Column('assistents', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('aar_completat', sa.Boolean(), nullable=True),
    sa.Column('notes_aar', sa.Text(), nullable=True),
    sa.Column('poi_mes_reaccio', sa.String(length=100), nullable=True),
    sa.Column('objeccio_principal', sa.String(length=100), nullable=True),
    sa.Column('cta_final', sa.String(length=200), nullable=True),
    sa.Column('temperatura_post', sa.Enum('fred', 'templat', 'calent', 'bullent', name='temperatura_post'), nullable=True),
    sa.ForeignKeyConstraint(['municipi_id'], ['municipis_lifecycle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trucades_v2',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('municipi_id', sa.UUID(), nullable=False),
    sa.Column('data', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('durada_minuts', sa.Integer(), nullable=True),
    sa.Column('qui_va_contestar', sa.Enum('alcalde', 'tecnic', 'cfo', name='actor_respuesta'), nullable=True),
    sa.Column('notes_breus', sa.Text(), nullable=True),
    sa.Column('resum_ia', sa.Text(), nullable=True),
    sa.Column('seguent_accio_sugerida', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['municipi_id'], ['municipis_lifecycle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trucades_v2')
    op.drop_table('reunions_v2')
    op.drop_table('memoria_municipis')
    op.drop_table('emails_v2')
    op.drop_table('patrons_municipis')
    op.drop_index(op.f('ix_municipis_lifecycle_nom'), table_name='municipis_lifecycle')
    op.drop_index(op.f('ix_municipis_lifecycle_etapa_actual'), table_name='municipis_lifecycle')
    op.drop_table('municipis_lifecycle')
    op.drop_table('contactes_v2')
    # ### end Alembic commands ###
