"""Add tactical memory columns to memoria_municipis

Revision ID: d2e76c3d5531
Revises: f2b2c2d2e2f2
Create Date: 2026-04-09 17:49:36.639233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd2e76c3d5531'
down_revision: Union[str, Sequence[str], None] = 'f2b2c2d2e2f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_memories_v2',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('municipi_id', sa.UUID(), nullable=False),
    sa.Column('clau', sa.String(length=50), nullable=True),
    sa.Column('valor', sa.Text(), nullable=True),
    sa.Column('confidenca', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['municipi_id'], ['municipis_lifecycle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_memories_v2_clau'), 'agent_memories_v2', ['clau'], unique=False)
    op.create_table('tasques_v2',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('municipi_id', sa.UUID(), nullable=False),
    sa.Column('titol', sa.String(length=200), nullable=False),
    sa.Column('descripcio', sa.Text(), nullable=True),
    sa.Column('data_venciment', sa.DateTime(), nullable=True),
    sa.Column('prioritat', sa.String(length=20), nullable=True),
    sa.Column('estat', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['municipi_id'], ['municipis_lifecycle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('activitats_municipi', 'tipus_activitat',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('nota_manual', 'email_enviat', 'email_rebut', 'trucada', 'reunio', 'demo', 'pagament', 'canvi_etapa', 'sistema', name='tipus_activitat', native_enum=False),
               existing_nullable=False)
    op.alter_column('activitats_municipi', 'data_activitat',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('activitats_municipi', 'etiquetes',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=sa.ARRAY(sa.String()),
               existing_nullable=True)
    op.create_foreign_key(None, 'activitats_municipi', 'deals', ['deal_id'], ['id'])
    op.alter_column('contactes_v2', 'carrec',
               existing_type=postgresql.ENUM('alcalde', 'regidor_turisme', 'tecnic', 'cfo', 'regidor_cultura', 'altre', name='carrec'),
               type_=sa.Enum('alcalde', 'regidor_turisme', 'tecnic', 'cfo', 'regidor_cultura', 'altre', name='carrec', native_enum=False),
               existing_nullable=False)
    op.alter_column('contactes_v2', 'to_preferit',
               existing_type=postgresql.ENUM('formal', 'proxim', 'tecnic', name='to_comunicacio'),
               type_=sa.Enum('formal', 'proxim', 'tecnic', name='to_comunicacio', native_enum=False),
               existing_nullable=True)
    op.add_column('email_drafts_v2', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('email_drafts_v2', 'estat',
               existing_type=postgresql.ENUM('esborrany', 'revisat', 'enviat', 'programat', name='estat_draft'),
               type_=sa.Enum('esborrany', 'revisat', 'enviat', 'programat', name='estat_draft', native_enum=False),
               existing_nullable=True,
               existing_server_default=sa.text("'esborrany'::estat_draft"))
    op.drop_column('email_drafts_v2', 'data_creacio')
    op.alter_column('email_sequencies_v2', 'tipus_sequencia',
               existing_type=postgresql.ENUM('prospeccio', 'seguiment', 'nurture', 'recuperacio', name='tipus_sequencia'),
               type_=sa.Enum('prospeccio', 'seguiment', 'nurture', 'recuperacio', name='tipus_sequencia', native_enum=False),
               existing_nullable=False)
    op.alter_column('email_sequencies_v2', 'estat',
               existing_type=postgresql.ENUM('pendent', 'preparant', 'preparat', 'programat', 'enviat', 'obert', 'respost', 'no_obert', 'cancelat', name='estat_sequencia'),
               type_=sa.Enum('pendent', 'preparant', 'preparat', 'programat', 'enviat', 'obert', 'respost', 'no_obert', 'cancelat', name='estat_sequencia', native_enum=False),
               existing_nullable=True,
               existing_server_default=sa.text("'pendent'::estat_sequencia"))
    op.alter_column('emails_v2', 'sentiment_resposta',
               existing_type=postgresql.ENUM('positiu', 'neutre', 'negatiu', 'confus', name='sentiment'),
               type_=sa.Enum('positiu', 'neutre', 'negatiu', 'confus', name='sentiment', native_enum=False),
               existing_nullable=True)
    op.alter_column('emails_v2', 'actor_probable',
               existing_type=postgresql.ENUM('alcalde', 'tecnic', 'cfo', name='actor'),
               type_=sa.Enum('alcalde', 'tecnic', 'cfo', name='actor', native_enum=False),
               existing_nullable=True)
    op.add_column('memoria_municipis', sa.Column('resum_tactic', sa.Text(), nullable=True))
    op.add_column('memoria_municipis', sa.Column('data_resum', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('municipis_lifecycle', 'geografia',
               existing_type=postgresql.ENUM('muntanya', 'mar', 'interior', 'city', name='geografia'),
               type_=sa.Enum('muntanya', 'mar', 'interior', 'city', name='geografia', native_enum=False),
               existing_nullable=True)
    op.alter_column('municipis_lifecycle', 'etapa_actual',
               existing_type=postgresql.ENUM('research', 'contacte', 'demo_pendent', 'demo_ok', 'oferta', 'documentacio', 'aprovacio', 'contracte', 'client', 'pausa', 'perdut', name='etapa_funnel'),
               type_=sa.Enum('research', 'contacte', 'demo_pendent', 'demo_ok', 'oferta', 'documentacio', 'aprovacio', 'contracte', 'client', 'pausa', 'perdut', name='etapa_funnel', native_enum=False),
               existing_nullable=True,
               existing_server_default=sa.text("'research'::etapa_funnel"))
    op.alter_column('municipis_lifecycle', 'blocker_actual',
               existing_type=postgresql.ENUM('alcalde', 'tecnic', 'cfo', 'temporitzacio', 'cap', name='blocker'),
               type_=sa.Enum('alcalde', 'tecnic', 'cfo', 'temporitzacio', 'cap', name='blocker', native_enum=False),
               existing_nullable=True,
               existing_server_default=sa.text("'cap'::blocker"))
    op.alter_column('municipis_lifecycle', 'temperatura',
               existing_type=postgresql.ENUM('fred', 'templat', 'calent', 'bullent', name='temperatura'),
               type_=sa.Enum('fred', 'templat', 'calent', 'bullent', name='temperatura', native_enum=False),
               existing_nullable=True,
               existing_server_default=sa.text("'fred'::temperatura"))
    op.alter_column('municipis_lifecycle', 'pla_contractat',
               existing_type=postgresql.ENUM('Roure', 'Mirador', 'Territori', name='pla'),
               type_=sa.Enum('Roure', 'Mirador', 'Territori', name='pla', native_enum=False),
               existing_nullable=True)
    op.alter_column('municipis_lifecycle', 'estat_final',
               existing_type=postgresql.ENUM('client', 'perdut', 'pausa', name='estat_final'),
               type_=sa.Enum('client', 'perdut', 'pausa', name='estat_final', native_enum=False),
               existing_nullable=True)
    op.create_index(op.f('ix_municipis_lifecycle_etapa_actual'), 'municipis_lifecycle', ['etapa_actual'], unique=False)
    op.create_index(op.f('ix_municipis_lifecycle_nom'), 'municipis_lifecycle', ['nom'], unique=False)
    op.alter_column('patrons_municipis', 'tipus_geografia',
               existing_type=postgresql.ENUM('muntanya', 'mar', 'interior', 'city', name='geografia_patro'),
               type_=sa.Enum('muntanya', 'mar', 'interior', 'city', name='geografia_patro', native_enum=False),
               existing_nullable=True)
    op.alter_column('reunions_v2', 'temperatura_post',
               existing_type=postgresql.ENUM('fred', 'templat', 'calent', 'bullent', name='temperatura_post'),
               type_=sa.Enum('fred', 'templat', 'calent', 'bullent', name='temperatura_post', native_enum=False),
               existing_nullable=True)
    op.alter_column('trucades_v2', 'qui_va_contestar',
               existing_type=postgresql.ENUM('alcalde', 'tecnic', 'cfo', name='actor_respuesta'),
               type_=sa.Enum('alcalde', 'tecnic', 'cfo', name='actor_respuesta', native_enum=False),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trucades_v2', 'qui_va_contestar',
               existing_type=sa.Enum('alcalde', 'tecnic', 'cfo', name='actor_respuesta', native_enum=False),
               type_=postgresql.ENUM('alcalde', 'tecnic', 'cfo', name='actor_respuesta'),
               existing_nullable=True)
    op.alter_column('reunions_v2', 'temperatura_post',
               existing_type=sa.Enum('fred', 'templat', 'calent', 'bullent', name='temperatura_post', native_enum=False),
               type_=postgresql.ENUM('fred', 'templat', 'calent', 'bullent', name='temperatura_post'),
               existing_nullable=True)
    op.alter_column('patrons_municipis', 'tipus_geografia',
               existing_type=sa.Enum('muntanya', 'mar', 'interior', 'city', name='geografia_patro', native_enum=False),
               type_=postgresql.ENUM('muntanya', 'mar', 'interior', 'city', name='geografia_patro'),
               existing_nullable=True)
    op.drop_index(op.f('ix_municipis_lifecycle_nom'), table_name='municipis_lifecycle')
    op.drop_index(op.f('ix_municipis_lifecycle_etapa_actual'), table_name='municipis_lifecycle')
    op.alter_column('municipis_lifecycle', 'estat_final',
               existing_type=sa.Enum('client', 'perdut', 'pausa', name='estat_final', native_enum=False),
               type_=postgresql.ENUM('client', 'perdut', 'pausa', name='estat_final'),
               existing_nullable=True)
    op.alter_column('municipis_lifecycle', 'pla_contractat',
               existing_type=sa.Enum('Roure', 'Mirador', 'Territori', name='pla', native_enum=False),
               type_=postgresql.ENUM('Roure', 'Mirador', 'Territori', name='pla'),
               existing_nullable=True)
    op.alter_column('municipis_lifecycle', 'temperatura',
               existing_type=sa.Enum('fred', 'templat', 'calent', 'bullent', name='temperatura', native_enum=False),
               type_=postgresql.ENUM('fred', 'templat', 'calent', 'bullent', name='temperatura'),
               existing_nullable=True,
               existing_server_default=sa.text("'fred'::temperatura"))
    op.alter_column('municipis_lifecycle', 'blocker_actual',
               existing_type=sa.Enum('alcalde', 'tecnic', 'cfo', 'temporitzacio', 'cap', name='blocker', native_enum=False),
               type_=postgresql.ENUM('alcalde', 'tecnic', 'cfo', 'temporitzacio', 'cap', name='blocker'),
               existing_nullable=True,
               existing_server_default=sa.text("'cap'::blocker"))
    op.alter_column('municipis_lifecycle', 'etapa_actual',
               existing_type=sa.Enum('research', 'contacte', 'demo_pendent', 'demo_ok', 'oferta', 'documentacio', 'aprovacio', 'contracte', 'client', 'pausa', 'perdut', name='etapa_funnel', native_enum=False),
               type_=postgresql.ENUM('research', 'contacte', 'demo_pendent', 'demo_ok', 'oferta', 'documentacio', 'aprovacio', 'contracte', 'client', 'pausa', 'perdut', name='etapa_funnel'),
               existing_nullable=True,
               existing_server_default=sa.text("'research'::etapa_funnel"))
    op.alter_column('municipis_lifecycle', 'geografia',
               existing_type=sa.Enum('muntanya', 'mar', 'interior', 'city', name='geografia', native_enum=False),
               type_=postgresql.ENUM('muntanya', 'mar', 'interior', 'city', name='geografia'),
               existing_nullable=True)
    op.drop_column('memoria_municipis', 'data_resum')
    op.drop_column('memoria_municipis', 'resum_tactic')
    op.alter_column('emails_v2', 'actor_probable',
               existing_type=sa.Enum('alcalde', 'tecnic', 'cfo', name='actor', native_enum=False),
               type_=postgresql.ENUM('alcalde', 'tecnic', 'cfo', name='actor'),
               existing_nullable=True)
    op.alter_column('emails_v2', 'sentiment_resposta',
               existing_type=sa.Enum('positiu', 'neutre', 'negatiu', 'confus', name='sentiment', native_enum=False),
               type_=postgresql.ENUM('positiu', 'neutre', 'negatiu', 'confus', name='sentiment'),
               existing_nullable=True)
    op.alter_column('email_sequencies_v2', 'estat',
               existing_type=sa.Enum('pendent', 'preparant', 'preparat', 'programat', 'enviat', 'obert', 'respost', 'no_obert', 'cancelat', name='estat_sequencia', native_enum=False),
               type_=postgresql.ENUM('pendent', 'preparant', 'preparat', 'programat', 'enviat', 'obert', 'respost', 'no_obert', 'cancelat', name='estat_sequencia'),
               existing_nullable=True,
               existing_server_default=sa.text("'pendent'::estat_sequencia"))
    op.alter_column('email_sequencies_v2', 'tipus_sequencia',
               existing_type=sa.Enum('prospeccio', 'seguiment', 'nurture', 'recuperacio', name='tipus_sequencia', native_enum=False),
               type_=postgresql.ENUM('prospeccio', 'seguiment', 'nurture', 'recuperacio', name='tipus_sequencia'),
               existing_nullable=False)
    op.add_column('email_drafts_v2', sa.Column('data_creacio', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.alter_column('email_drafts_v2', 'estat',
               existing_type=sa.Enum('esborrany', 'revisat', 'enviat', 'programat', name='estat_draft', native_enum=False),
               type_=postgresql.ENUM('esborrany', 'revisat', 'enviat', 'programat', name='estat_draft'),
               existing_nullable=True,
               existing_server_default=sa.text("'esborrany'::estat_draft"))
    op.drop_column('email_drafts_v2', 'created_at')
    op.alter_column('contactes_v2', 'to_preferit',
               existing_type=sa.Enum('formal', 'proxim', 'tecnic', name='to_comunicacio', native_enum=False),
               type_=postgresql.ENUM('formal', 'proxim', 'tecnic', name='to_comunicacio'),
               existing_nullable=True)
    op.alter_column('contactes_v2', 'carrec',
               existing_type=sa.Enum('alcalde', 'regidor_turisme', 'tecnic', 'cfo', 'regidor_cultura', 'altre', name='carrec', native_enum=False),
               type_=postgresql.ENUM('alcalde', 'regidor_turisme', 'tecnic', 'cfo', 'regidor_cultura', 'altre', name='carrec'),
               existing_nullable=False)
    op.drop_constraint(None, 'activitats_municipi', type_='foreignkey')
    op.alter_column('activitats_municipi', 'etiquetes',
               existing_type=sa.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
    op.alter_column('activitats_municipi', 'data_activitat',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('activitats_municipi', 'tipus_activitat',
               existing_type=sa.Enum('nota_manual', 'email_enviat', 'email_rebut', 'trucada', 'reunio', 'demo', 'pagament', 'canvi_etapa', 'sistema', name='tipus_activitat', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_table('tasques_v2')
    op.drop_index(op.f('ix_agent_memories_v2_clau'), table_name='agent_memories_v2')
    op.drop_table('agent_memories_v2')
    # ### end Alembic commands ###
