"""Add tactical memory columns to memoria_municipis

Revision ID: d2e76c3d5531
Revises: f2b2c2d2e2f2
Create Date: 2026-04-09 17:49:36.639233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd2e76c3d5531'
down_revision: Union[str, Sequence[str], None] = 'f2b2c2d2e2f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_memories_v2',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('municipi_id', sa.UUID(), nullable=False),
    sa.Column('clau', sa.String(length=50), nullable=True),
    sa.Column('valor', sa.Text(), nullable=True),
    sa.Column('confidenca', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['municipi_id'], ['municipis_lifecycle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_memories_v2_clau'), 'agent_memories_v2', ['clau'], unique=False)
    op.create_table('tasques_v2',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('municipi_id', sa.UUID(), nullable=False),
    sa.Column('titol', sa.String(length=200), nullable=False),
    sa.Column('descripcio', sa.Text(), nullable=True),
    sa.Column('data_venciment', sa.DateTime(), nullable=True),
    sa.Column('prioritat', sa.String(length=20), nullable=True),
    sa.Column('estat', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['municipi_id'], ['municipis_lifecycle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasques_v2')
    op.drop_index(op.f('ix_agent_memories_v2_clau'), table_name='agent_memories_v2')
    op.drop_table('agent_memories_v2')
    # ### end Alembic commands ###
