"""add_drafts_and_sequences

Revision ID: e40234ee066b
Revises: cbd00bad276d
Create Date: 2026-03-17 21:30:51.958858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e40234ee066b'
down_revision: Union[str, Sequence[str], None] = 'cbd00bad276d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_drafts_v2',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('municipi_id', sa.UUID(), nullable=False),
    sa.Column('contacte_id', sa.UUID(), nullable=True),
    sa.Column('estat', sa.Enum('esborrany', 'revisat', 'enviat', 'programat', name='estat_draft'), nullable=True),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('cos', sa.Text(), nullable=True),
    sa.Column('generat_per_ia', sa.Boolean(), nullable=True),
    sa.Column('prompt_utilitzat', sa.Text(), nullable=True),
    sa.Column('variants_generades', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('variant_seleccionada', sa.Integer(), nullable=True),
    sa.Column('editat_per_usuari', sa.Boolean(), nullable=True),
    sa.Column('canvis_respecte_ia', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('data_enviament', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enviat_des_de', sa.String(length=100), nullable=True),
    sa.Column('email_enviat_id', sa.UUID(), nullable=True),
    sa.Column('data_creacio', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['contacte_id'], ['contactes_v2.id'], ),
    sa.ForeignKeyConstraint(['email_enviat_id'], ['emails_v2.id'], ),
    sa.ForeignKeyConstraint(['municipi_id'], ['municipis_lifecycle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_sequencies_v2',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('municipi_id', sa.UUID(), nullable=False),
    sa.Column('numero_email', sa.Integer(), nullable=False),
    sa.Column('tipus_sequencia', sa.Enum('prospeccio', 'seguiment', 'nurture', 'recuperacio', name='tipus_sequencia'), nullable=False),
    sa.Column('estat', sa.Enum('pendent', 'preparant', 'preparat', 'programat', 'enviat', 'obert', 'respost', 'no_obert', 'cancelat', name='estat_sequencia'), nullable=True),
    sa.Column('data_programada', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_enviada', sa.DateTime(timezone=True), nullable=True),
    sa.Column('draft_id', sa.UUID(), nullable=True),
    sa.Column('obert', sa.Boolean(), nullable=True),
    sa.Column('data_obertura', sa.DateTime(timezone=True), nullable=True),
    sa.Column('respost', sa.Boolean(), nullable=True),
    sa.Column('seguent_accio', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['draft_id'], ['email_drafts_v2.id'], ),
    sa.ForeignKeyConstraint(['municipi_id'], ['municipis_lifecycle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_sequencies_v2')
    op.drop_table('email_drafts_v2')
    # ### end Alembic commands ###
